// Code generated by goctl. DO NOT EDIT.
// Source: demo.proto

package server

import (
	"context"

	"github.com/Sion-L/go-zero-demo/demo/demo"
	"github.com/Sion-L/go-zero-demo/demo/internal/logic"
	"github.com/Sion-L/go-zero-demo/demo/internal/svc"
)

type MyDemoServer struct {
	svcCtx *svc.ServiceContext
	demo.UnimplementedMyDemoServer
}

func NewMyDemoServer(svcCtx *svc.ServiceContext) *MyDemoServer {
	return &MyDemoServer{
		svcCtx: svcCtx,
	}
}

func (s *MyDemoServer) Demo(ctx context.Context, in *demo.DemoReq) (*demo.DemoRes, error) {
	l := logic.NewDemoLogic(ctx, s.svcCtx)
	return l.Demo(in)
}
