// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	demo "github.com/Sion-L/go-zero-demo/gateway/internal/handler/demo"
	shorturl "github.com/Sion-L/go-zero-demo/gateway/internal/handler/shorturl"
	"github.com/Sion-L/go-zero-demo/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: demo.DemoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/demo"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/expand",
				Handler: shorturl.ExpandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shorten",
				Handler: shorturl.ShortenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/shorturl"),
	)
}
