// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: demo.proto

package demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MyDemo_Demo_FullMethodName = "/demo.myDemo/demo"
)

// MyDemoClient is the client API for MyDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyDemoClient interface {
	Demo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoRes, error)
}

type myDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewMyDemoClient(cc grpc.ClientConnInterface) MyDemoClient {
	return &myDemoClient{cc}
}

func (c *myDemoClient) Demo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DemoRes)
	err := c.cc.Invoke(ctx, MyDemo_Demo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyDemoServer is the server API for MyDemo service.
// All implementations must embed UnimplementedMyDemoServer
// for forward compatibility.
type MyDemoServer interface {
	Demo(context.Context, *DemoReq) (*DemoRes, error)
	mustEmbedUnimplementedMyDemoServer()
}

// UnimplementedMyDemoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMyDemoServer struct{}

func (UnimplementedMyDemoServer) Demo(context.Context, *DemoReq) (*DemoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Demo not implemented")
}
func (UnimplementedMyDemoServer) mustEmbedUnimplementedMyDemoServer() {}
func (UnimplementedMyDemoServer) testEmbeddedByValue()                {}

// UnsafeMyDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyDemoServer will
// result in compilation errors.
type UnsafeMyDemoServer interface {
	mustEmbedUnimplementedMyDemoServer()
}

func RegisterMyDemoServer(s grpc.ServiceRegistrar, srv MyDemoServer) {
	// If the following call pancis, it indicates UnimplementedMyDemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MyDemo_ServiceDesc, srv)
}

func _MyDemo_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyDemoServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MyDemo_Demo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyDemoServer).Demo(ctx, req.(*DemoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MyDemo_ServiceDesc is the grpc.ServiceDesc for MyDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "demo.myDemo",
	HandlerType: (*MyDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "demo",
			Handler:    _MyDemo_Demo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}
