// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	User     string `json:"user"`
	Password string `json:"password"`
}

type DemoReq struct {
	Name string `path:"name,options=you|me"`
}

type DemoRes struct {
	Message string `json:"message"`
}

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type GatewayResponse struct {
	Data interface{} `json:"data"`
	Flag bool        `json:"flag"`
	Msg  string      `json:"msg"`
	Code int         `json:"code"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}
